### PR TITLE
Ready to flow

### PR DESCRIPTION
**Pull request by tomasz-sodzawiczny**

### CODE REVIEW

**Comment by kdzwinel** [comment]
no idea what's happening in that config, is it a default?

**Comment by tomasz-sodzawiczny** [comment]
@kdzwinel most of it is default (syntax, spaces, etc).

I disabled the most aggressive rules (enforcing explicit declarations of all functions, not using "weak" types) - I think it will be easier to start this way and then we can work out some better rules.

**Comment by kdzwinel** [comment]
ok, thanks for explanation

**Comment by tomasz-sodzawiczny** [comment]
@kdzwinel Also I talked briefly with @aju about this: I left the default spacing on type annotations and default name schema so we'll have:
```js
type MyComponentPropsType = {} // OK!
type MyComponentProps = {} // Error, has to end with "Type"

props: MyComponentPropsType // OK (no space before the colon)!
props : MyComponentPropsType // Some people use the extra space to differentiate from object field definitions
```

**Pull request merged**
