### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by aju**
I have updated all rules to match order and groups on page:
http://eslint.org/docs/rules/

All recommended rules are enabled. I have enabled some additional rules as well (mostly from es6 group and best practices)

There is over 100 errors in symfony es6 files right now.
Most of them referes to:
no-undef - http://eslint.org/docs/rules/no-undef
sort-imports - http://eslint.org/docs/rules/sort-imports
no-unused-vars - disallow unused variables

WDYT about this setup?

### CODE REVIEW

**Comment by kdzwinel** [comment]
1) It's hard to tell which rules you have changed bacause everything changed places. Can you give us some info on what was enabled/disabled.

2) sort-imports - sorting thing alphabetically seems like a bit too much IMO, I'd drop that

3) no-unused-vars - this will be problematic to fix, we already do not allow creating object without assigning them to a variable - usualy this was fixed by creating a dummy variable, now it won't work

**Comment by aju** [comment]
2) check what this rule really does. :)

**Comment by kdzwinel** [comment]
2) I did. This is incorrect because it's not alphabetically:

```
import b from 'foo.js';
import a from 'bar.js';
```

**Comment by aju** [comment]
But still it will help with grouping imports by category. I think I can fix it but if you prefer to disable it its ok for me.

3) no-unused-vars - true I will check if our current setup will allow fixing it if no I will disable it

1) All in group // POSSIBLE ERRORS + ECMAScript 6
"array-callback-return": "error",
"no-empty-function": "error",
// disallow unnecessary labels
"no-extra-label": "error",
// disallow fallthrough of case statements
"no-fallthrough": "error",
// disallow var and named function declarations in the global scope
 "no-implicit-globals": "error",
"array-bracket-spacing": ["error", "never"],
 "block-spacing": ["error", "never"],
"comma-spacing": ["error", { "before": false, "after": true }],
"comma-dangle": ["error", "never"],
// enforce spacing before and after keywords
"keyword-spacing": ["error", {"before": true, "after": true}],
"no-whitespace-before-property": "error",
"unicode-bom": ["error", "never"],

**Comment by kdzwinel** [comment]
2) lets do not add it
3) see if code is fixable in a reasonable way before merging this

remember to bump the version of the config!

OK

**Comment by aju** [comment]
Will do first I will try to fix code then merge this PR :)

**Comment by matzimowski** [comment]
👍 for skipping 2
i am okay with the rest ❤️ 
OK

**Comment by matzimowski** [comment]
OK

**Comment by kdzwinel** [comment]
OK

**Pull request merged**
